name: Release functions to azure function
on: 
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - 'functions/**'


permissions:
  id-token: write
  contents: read
env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'functions' # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: '3.11' 
  AZURE_FUNCTIONAPP_NAME: 'fn-don-sad-d-eun-01'
  AZURE_FUNCTIONAPP_RG: 'rg-don-sad-d-eun-01'
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: 'Resolve Project Dependencies Using Pip'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"
          popd

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: |
            ./functions
      
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: "Zip files for deployment"
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          zip python-app.zip *
          popd
        
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.60.0
          inlineScript: |
            az functionapp deployment source config-zip -g ${{ env.AZURE_FUNCTIONAPP_RG }} -n ${{ env.AZURE_FUNCTIONAPP_NAME }} --src ./functions/python-app.zip